### ISSUE TITLE
[Feature Request] plain text output of domains only option.

### ISSUE THREAD

**Issue by gprime31** [guelfoweb/knock#104]
plain text output, example: 

example.com
sub.exaplle.com
apple.com
sub.apple.com
microsoft.com
sub.mircosoft.com
etc...

**Comment by Lolo21-ui** [comment]
I am also getting the same problem
i triend installing colorama but it still shows items in plain.

**Comment by guelfoweb** [comment]
You can use [--csv](https://github.com/guelfoweb/knock#csv-report) option with the release 5.1.0

**Comment by gprime31** [comment]
> You can use [--csv](https://github.com/guelfoweb/knock#csv-report) option with the release 5.1.0

thanks, converts to .csv file and I can copy out the domain column.
