### ISSUE TITLE
knockpy 5.1.0 pyqt5 error

### ISSUE THREAD

**Issue by gprime31** [guelfoweb/knock#105]
$ pip3 install PyQt5
Collecting PyQt5
   Using cached https://files.pythonhosted.org/packages/3a/fb/eb51731f2dc7c22d8e1a63ba88fb702727b324c6352183a32f27f73b8116/PyQt5-5.14.1.tar.gz
   Installing build dependencies ... done
     Complete output from command python setup.py egg_info:
     Traceback (most recent call last):
       File "<string>", line 1, in <module>
       File "/usr/lib/python3.7/tokenize.py", line 447, in open
         buffer = _builtin_open(filename, 'rb')
     FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-0q6_olh9/PyQt5/setup.py'

$ pip3 install -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement pyqt5 (from versions: none)
ERROR: No matching distribution found for pyqt5

running knockpy -v
pkg_resources.DistributionNotFound: The 'PyQt5' distribution was not found and is required by knockpy

**Comment by gprime31** [comment]
Forget to mention it can be run ./knockpy.py and everything works good. just the installer does not.

**Comment by gprime31** [comment]
$ pip3 install --user PyQt5
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement PyQt5 (from versions: none)
ERROR: No matching distribution found for PyQt5

same with the other commands.

**Comment by guelfoweb** [comment]
You are using Python2 but knockpy needs [Python3 ](https://github.com/guelfoweb/knock#you-need-python3-pip3-git)

**Comment by gprime31** [comment]
> You are using Python2 but knockpy needs [Python3 ](https://github.com/guelfoweb/knock#you-need-python3-pip3-git)

pip3 can't be python2.

**Comment by gprime31** [comment]
here is from: python3 -m pip install PyQt5

 python3 -m pip install PyQt5
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting PyQt5
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/8e/a4/d5e4bf99dd50134c88b95e926d7b81aad2473b47fde5e3e4eac2c69a8942/PyQt5-5.15.4.tar.gz
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-rva3nxhh/PyQt5/setup.py'

**Comment by gprime31** [comment]
But going to close, like i said earlier running from ./knockpy works fine
Great tool :)
