### ISSUE TITLE
plugin_test vs plugin-test

### ISSUE THREAD

**Issue by SirCussFreq** [guelfoweb/knock#131]
just some inconsistency in the code, most places reference --plugin_test, but some say it should be --plugin-test.  

e.g. 

if_params["plugin_test']

vs

parser.add_argument("--plugin-test", ...

I _think_ you just need to change add_argument to plugin_test, but I haven't tested it yet.  (and update relevant documentation)

**Comment by guelfoweb** [comment]
Dashes in argparse are converted to underscores ([link](https://stackoverflow.com/a/12834980))
