### ISSUE TITLE
Circular include

### ISSUE THREAD

**Issue by wu4f** [guelfoweb/knock#154]
This import in knockpy.py seems to cause a circular include...
`from knockpy import knockpy
`
It is fixed by changing the import to
`from knock import knockpy`
===========
[~/knock][master *] % python3 knockpy.py -d pdx.edu
Traceback (most recent call last):
  File "/usr/local/home/wuchang/knock/knockpy.py", line 7, in <module>
    from knockpy import knockpy
  File "/usr/local/home/wuchang/knock/knockpy.py", line 7, in <module>
    from knockpy import knockpy
ImportError: cannot import name 'knockpy' from partially initialized module 'knockpy' (most likely due to a circular import) (/usr/local/home/wuchang/knock/knockpy.py)

**Comment by drego85** [comment]
Bye,
as stated in the README you have to install Knock via this command:
`pip install git+https://github.com/guelfoweb/knock.git
`
Then you can use the command `knockpy -d pdx.edu` to perform your scan.
