### ISSUE TITLE
Issues in script Knock.py

### ISSUE THREAD

**Issue by unmesh92** [guelfoweb/knock#26]
Dear Team,

I am getting following issues while running the script:-

^CTraceback (most recent call last):
  File "/usr/bin/knockpy", line 9, in <module>
    load_entry_point('knockpy==3.0', 'console_scripts', 'knockpy')()
  File "/usr/lib/python2.7/dist-packages/knockpy/knockpy.py", line 136, in main
    start(domain)
  File "/usr/lib/python2.7/dist-packages/knockpy/knockpy.py", line 59, in start
    core.subdomain_scan()
  File "/usr/lib/python2.7/dist-packages/knockpy/modules/core.py", line 217, in subdomain_scan
    result = get_target(target, False, False)
  File "/usr/lib/python2.7/dist-packages/knockpy/modules/core.py", line 49, in get_target
    return target.get(_target, verbose, test)
  File "/usr/lib/python2.7/dist-packages/knockpy/modules/target.py", line 30, in get
    result = subscan.start(target)
  File "/usr/lib/python2.7/dist-packages/knockpy/modules/subscan.py", line 31, in start

Please help me out to resolve the above issues

Best Regards,
Uemsh Jore

**Comment by tomdev** [comment]
@unmesh92 Please provide more information to help debugging. Just dumping an error message usually doesn't cut it.

On what platform are you running? 
What version of python are you using? 
How did you install knockpy?
What command do you use to run knockpy?

**Comment by rajkumar80** [comment]
Hi Tomdev

Can you pls. help me in installing the knockpy. I've searched for installation of knockpy but I am unable to. In the old one, I am getting the same error, so pls. help me with the new installation.

Best regards
Rjkumar

**Comment by tomdev** [comment]
@rajkumar80  

On what platform are you running?
What version of python are you using?
How did you install knockpy?
What command do you use to run knockpy?

**Comment by rajkumar80** [comment]
Hi Tomdev

I've solved the problem myself. I've downloaded and inserted the following command and it worked perfectly. This is the command python knockpy.py <URL> -w /usr/local/lib/python2.7/dist-packages/knockpy/wordlist.txt

I need someone who can help me with knockpy in the whole, can you pls. help me on how to work with this tool and how to find subdomains to take over.

Best regards
RajKumar

**Comment by unmesh92** [comment]
Hi Rajkumar,

Download backbox Linux.
Knock.py is already present in it.

Best Regards,

Umesh Jore

**Comment by sahil-dhuri** [comment]
virtualbox kali linux
virus total api key not found
resolving target:no

**Comment by KleopIn** [comment]
Hello 
 Can you help me, I can’t understand how to use the tool, I installed it as written in the instructions, I use it as follows: python knockpy.py DOMEN gives a traceback error

**Comment by drego85** [comment]
This is an issue over 6 years old and already resolved, for those who have further issues please open a new issue detailed and accurate!
