### ISSUE TITLE
Virustotal API Key not Found!

### ISSUE THREAD

**Issue by zerocode29** [guelfoweb/knock#44]
Hello when I try to resolve any domain using knockpy -r the error appeared that virustotal API key not found while I already configured my virustotal API key in config.json file. What issue?

**Comment by newaynewlife** [comment]
You must set the API key before install or use the command:python knockpy/knockpy.py domain.com

**Comment by Darkerhack** [comment]
Yaa, Right If you Not get then reinstall again It Worked for me.
