### ISSUE TITLE
Update the installation instruction 

### ISSUE THREAD

**Issue by Anupam-Yadav** [guelfoweb/knock#69]
$ cd knock
$ cd knockpy
$ python knockpy.py DOMAIN.COM

**Comment by thomasmerz** [comment]
This is not "how to install", but "how to run" `knockpy`…

**Comment by drego85** [comment]
The current description is correct: [git clone https://github.com/guelfoweb/knock.git](https://github.com/guelfoweb/knock/blob/master/README.md#install)
