### ISSUE TITLE
No module names python-dnspython

### ISSUE THREAD

**Issue by mrhydra-np** [guelfoweb/knock#83]
It says try pip install dnspython
So, when i run that command the result is requirement already satisfied😕. How can i make it detect dnspython any solution?!☹️

**Comment by benchacham** [comment]
Same issue ....
Somebody can solve it?

**Comment by Sidodus** [comment]
This worked for me...

`sudo apt-get install pip`
`sudo pip install dnspython`

**Comment by drego85** [comment]
dnspython has been removed from the new Knock version.
